### ISSUE TITLE
Syntax error when using 'async with' 

### ISSUE THREAD

**Issue by brewston** [andrewsayre/pysmartthings#1]
Python 3.6.6
aiohttp: 3.5.4
pysmarthings: 0.4.2

I have a virtualised 3.6 environment and pretty much followed the code in your example but I keep getting : 

    async with aiohttp.ClientSession() as session:
             ^
SyntaxError: invalid syntax

My code : 

def main():
    async with aiohttp.ClientSession() as session:
        api = pysmartthings.SmartThings(session, MyToken)
        locations = await api.locations()
        print(len(locations))

I tried removing the async and await (as I'm not familiar with using those) and got : 

    raise TypeError("Use async with instead")
TypeError: Use async with instead

Thanks

**Comment by andrewsayre** [comment]
You have to define `main` as a coroutine: `async def main():`.  Then you run it in the event loop:

```
async def main():
   ...

loop = asyncio.get_event_loop()  
loop.run_until_complete(main())  
loop.close()
```

There's a number of good intro articles to `async/await`:
1. https://stackabuse.com/python-async-await-tutorial/
2. https://medium.freecodecamp.org/a-guide-to-asynchronous-programming-in-python-with-asyncio-232e2afa44f6
3. https://docs.python.org/3/library/asyncio-task.html

**Comment by brewston** [comment]
Thanks, I was just coming back to let you know I have it working as : 

async def locations():

   async with aiohttp.ClientSession() as session:
      api = pysmartthings.SmartThings(session, MyToken)
      locations = await api.locations()
      location = locations[0]
      print(location.name)

and then : 

def main():
   loop = asyncio.get_event_loop()
   loop.run_until_complete(locations())
