### ISSUE TITLE
AC Windfree support

### ISSUE THREAD

**Issue by tkislan** [andrewsayre/pysmartthings#13]
Would it be possible to have support for windfree AC?
I've checked the Smarthings "console", and it seems as it only a simple on/off switch there.
I would also want to add it to Home Assistant later
I am familiar with HA codebase, so I can help there with the implementation and with the testing.

```
supportedAcOptionalMode:
[off, windFree]
```
```
acOptionalMode: windFree
```

<img width="307" alt="Screenshot 2019-06-15 at 17 18 15" src="https://user-images.githubusercontent.com/5370798/59553177-97b8a080-8f91-11e9-9ef0-0a7dd1dfcbae.png">

**Comment by andrewsayre** [comment]
Should be doable, but these capabilities aren’t public/documented, so I’ll need to get the specs from ST to add to HA.  Let me reach out to them and we’ll go from there.

**Comment by tkislan** [comment]
Awesome. Please let me know, if you'll need some more info or help from me 👍

**Comment by andrewsayre** [comment]
Sorry for the delay on this.. so in talking with ST, these map to the following capabilities `custom.airConditionerOptionalMode` and `custom.autoCleaningMode`.  The custom capabilities are transitory and not sure it makes sense to add them to the library at this time.  Instead, I think a better approach would be to hack this into HA directly.  Today HA matches known capabilities against what's in the library and excludes everything else.  I could support having it add in any capability with the custom prefix and map it to a sensor directly.  Let me think about it...
