### ISSUE TITLE
Executing custom commands possible?

### ISSUE THREAD

**Issue by aeozyalcin** [andrewsayre/pysmartthings#17]
Hello (I hope this is OK to post a question here, I couldn't find a better place for it),

I was hoping someone could give me an idea on how I can execute custom commands on a device using this library. Specifically, I am talking about custom commands that are defined in a custom device handler. From the available documentation and studying the source code, the only commands the library seems to allow execution on are those that are default/required by the declared capabilities of a given device.

For example, I have a custom virtual presence sensor on Smartthings with switch, presence and battery capabilities. I am trying to use this python library to execute a custom command I have written into the device handler called "setBattery(value)", which sets the battery percentage for that device. Looking at ST documentation, battery capability has no defined commands, hence why I had to create a custom command. But now I am not really sure how to go about executing the custom command and passing an argument to it using this library.

Any suggestions are welcome! Thanks!

**Comment by andrewsayre** [comment]
Unfortunately, there is not a way to execute custom commands (or access custom attributes) as defined in a Groovy DTH through the public API.
