### ISSUE TITLE
SyntaxError: 'async with' outside async function

### ISSUE THREAD

**Issue by adnan2911** [andrewsayre/pysmartthings#20]
Hello 
I am using very simple code on raspberry pi using python 3 as below 

```
import aiohttp
import pysmartthings

token = 'xxxxxxx'

async with aiohttp.ClientSession() as session:
        api = pysmarthings.SmartThings(session,token)
        devices = await api.devices()
        print(len(devices))
```

but i am getting below error
SyntaxError: 'async with' outside async function

Kindly please help
Thanks
Adnan

**Comment by posborne** [comment]
Hi @adnan2911, you are correct that the snippet is not complete as provided.  With python asyncio you will need to put that fragment inside an `async` function.  You will also need to run the async function on a reactor.  Here's a complete example you can play with:

```python
#!/usr/bin/env python3
import aiohttp
import asyncio
import pysmartthings

token = '...'

async def print_devices():
    async with aiohttp.ClientSession() as session:
        api = pysmartthings.SmartThings(session, token)
        devices = await api.devices()
        for device in devices:
            print("{}: {}".format(device.device_id, device.label))


def main():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(print_devices())
    loop.close()

if __name__ == '__main__':
    main()
```

**Comment by adnan2911** [comment]
Thanks alot Paul, It worked with above code

Regards,
Adnan

**Comment by FelixAsch** [comment]
How can I change the mediaInputSource on my SmartTV?
Im new in programming with smartthings, so i don't get your doku.

Regards,
Felix
