### ISSUE TITLE
Clues for subscription?

### ISSUE THREAD

**Issue by aadeocs** [andrewsayre/pysmartthings#21]
It appears the "subscription.py" file has functionality to have the ST Hub to notify the python program that some event (e.g. motion detector tripped) had occurred?  Assuming that is true, is there an example, or other clues on how to get started with subscriptions?

**Comment by andrewsayre** [comment]
Push notifications are through the SmartApp API.  You can combine the functionality of `pysmartthings` and `pysmartapp` to achieve what you're describing.  In the future, I plan to combine these libraries.

For more information on how subscriptions work see: https://smartthings.developer.samsung.com/docs/smartapps/subscriptions.html

**Comment by andrewsayre** [comment]
This issue appears to be stale, if you're still having trouble, open a new one.
