### ISSUE TITLE
Creating devices in SmartThings?

### ISSUE THREAD

**Issue by smathieson** [andrewsayre/pysmartthings#23]
Hello,

Is such a thing possible? I want to expose my own devices into SmartThings. ATM I use virtual switches in ST and read those (which I sync to in my automations). However as the number of devices grows automations become unwieldy. Is it possible to "create" ST devices from local devices?

Thanks.

Sam.

**Comment by andrewsayre** [comment]
It is possible -- the concept is called "installing a device": https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#operation/installDevice

The library does not implement this operation or the necessary supporting functions (creating device profiles), but you can call these APIs directly.

**Comment by smathieson** [comment]
I see that, however installing a device also requires an app to be installed in smartthings I believe.

Do you think it is possible to do without the app?

**Comment by andrewsayre** [comment]
I'm not aware of a way with the public API to get around needing a SmartApp to create device profiles and install devices.

**Comment by smathieson** [comment]
Thanks I did not find anything either. Is pysmartthings capable of awaiting for a change in a device status? I am trying to figure out how things work (trying to port to Domoticz) but as I see it, there is a smart app that provides the callback to the devices when synced with home assistant. Is that about right? No websocket for smartthings or anything like that exists I believe?

**Comment by andrewsayre** [comment]
Correct - device updates follow an event-driven architecture and are pushed out from SmartThings to a webhook you host in your application and that is registered through the SmartApp concept.  You can combine the functionality of `pysmartapp` with `pysmartthings` which implements the contract interface for the webhook.  This is what Home Assistant does.

**Comment by smathieson** [comment]
Thanks very much. I am trying to create a simple app to create devices in smartthings to mirror the local devices. Your code has been very helpful in learning how. Thanks again!
