### ISSUE TITLE
Media devices support

### ISSUE THREAD

**Issue by PiotrMachowski** [andrewsayre/pysmartthings#24]
Would it be possible to add support for media devices (TVs, soundbars, etc,)?
It seems that there already is some basic support for them (appropriate capabilities and attribute names), but there are no dedicated methods for executing commands nor attributes to retrieve current value.

https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html#Media-Playback

**Comment by andrewsayre** [comment]
The "dedicated methods" are simply wrappers around the `command` method.  You can call this directly with the name of the capability and command passed as strings.

**Comment by PiotrMachowski** [comment]
I know that these are just wrappers, I have used them [here](https://github.com/PiotrMachowski/Home-Assistant-test-components-SmartThings/blob/master/custom_components/smartthings/media_player.py). Nevertheless it would be nice to include them in library itself.

**Comment by andrewsayre** [comment]
Nice!  You should consider submitting PRs to add your work to this library and HA.  I’d be more than happy to review and push through.

**Comment by PiotrMachowski** [comment]
I was planning to do it, but I haven't found time yet. I will try to do it as soon as possible. The only problem is that I don't have SmartThings TV to test, just a soundbar, so right now I have added only features supported by my device.

**Comment by andrewsayre** [comment]
I have a Samsung Smart TV and can help you make sure it works with both.
