### ISSUE TITLE
HUB device.status.refresh() with code 403

### ISSUE THREAD

**Issue by thalesgreco** [andrewsayre/pysmartthings#26]
I'm getting Error Code 403 when I try to get Status Refresh from SmartThings HUB Devices, the others works properly and the solution was exclude status from HUB. Is there anyone having the same issue?

I can't get ONLINE or OFFLINE status from hub anymore.

>   await device.status.refresh()
>   File "C:\Users\Thales Greco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pysmartthings\device.py", line 641, in refresh
>     data = await self._api.get_device_status(self.device_id)
>   File "C:\Users\Thales Greco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pysmartthings\api.py", line 125, in get_device_status
>     return await self.get(API_DEVICE_STATUS.format(device_id=device_id))
>   File "C:\Users\Thales Greco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pysmartthings\api.py", line 380, in get
>     return await self.request("get", self._api_base + resource, params)
>   File "C:\Users\Thales Greco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pysmartthings\api.py", line 376, in request
>     resp.raise_for_status()
>   File "C:\Users\Thales Greco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\client_reqrep.py", line 946, in raise_for_status
>     headers=self.headers)
> aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api.smartthings.com/v1/devices/4e649CENSORED8-e7f7862d3b44/status')

`

**Comment by andrewsayre** [comment]
The SmartThings API returns `403` when a) you don't have access or b) the resource isn't found.  It may be that your token doesn't have permission to read hub status or the hub doesn't support status.  There appears to be a health check API which may work instead (though `pysmartthings` currently have support for this): https://smartthings.developer.samsung.com/docs/devices/health.html

Note you need the `r:hubs` scope on your token.

**Comment by thalesgreco** [comment]
> The SmartThings API returns `403` when a) you don't have access or b) the resource isn't found. It may be that your token doesn't have permission to read hub status or the hub doesn't support status. There appears to be a health check API which may work instead (though `pysmartthings` currently have support for this): https://smartthings.developer.samsung.com/docs/devices/health.html
> 
> Note you need the `r:hubs` scope on your token.

I think you're right. Before the ST API update I used to have access to HUB as a normal device. Can you tell me how to get health information using pysmartthings? The only capability that comes with HUB is [bridge]

**Comment by andrewsayre** [comment]
Sorry typo - `pysmartthings` does not have this API supported at this time. PRs are welcome :)

As a work around you can call the underlying `request` method to directly hit the API and interpret the results: https://github.com/andrewsayre/pysmartthings/blob/dev/pysmartthings/api.py#L349.  You can access it from `SmartThings._service.request`

**Comment by thalesgreco** [comment]
> Sorry typo - `pysmartthings` does not have this API supported at this time. PRs are welcome :)
> 
> As a work around you can call the underlying `request` method to directly hit the API and interpret the results: https://github.com/andrewsayre/pysmartthings/blob/dev/pysmartthings/api.py#L349. You can access it from `SmartThings._service.request`

I was reading the page you sent me and I just realized that they changed the endpoint to get HUB information. Looking inside pysmartthings I couldn't see the endpoint /installed-hubs

Do you think I can easily add this new endpoint inside my pysmartthings library without conflict with whole code?

**Comment by andrewsayre** [comment]
Yeah it wouldn't conflict - just a new entity type.  I did some experimenting, I can't get `/installed-hubs/{HUB_ID}/health` to work at all even with the right OAuth scope.  But `/devices/{HUB_ID}/health` does work.  If you want to submit a PR, I would do one adding support for health status on devices -- add it as `device.health` with `device.health.refresh`.

**Comment by thalesgreco** [comment]
I got this error when I try to call apply_data: 

>  610, in apply_data
    for component_id, component in data["components"].items():
KeyError: 'components'

**Comment by andrewsayre** [comment]
This issue appears to be stale, if you're still having trouble, open a new one.
