### ISSUE TITLE
Update to Device Commands Example for Switch Status

### ISSUE THREAD

**Issue by KOEPKEJR** [andrewsayre/pysmartthings#30]
The example for setting a switch status does not work as written.

This line...
`result = await device.command("switch", "on")`
...gives the following error.
`TypeError: command() missing 1 required positional argument: 'command'`

To resolve the issue I had to account for the component in the call by passing an empty string (or "main" which is the default)
`result = await device.command("","switch", "on")`

**Comment by andrewsayre** [comment]
Fixed by https://github.com/andrewsayre/pysmartthings/commit/b09980542d198dce7e4d691e4336599a696a973a
