### ISSUE TITLE
presence sensor capability not updated

### ISSUE THREAD

**Issue by smathieson** [andrewsayre/pysmartthings#33]
Hello,

There seems to be no way to update a presence sensor using pysmartthings. Do not understand why exactly. Can Presence be updated? Seems like the presence attribute does not exist in the states dictionary. Even after adding and a refresh seems like nothing is updated.

Thanks and regards,
Sam.

**Comment by andrewsayre** [comment]
A device that implements [presenceSensor capability](https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html#Presence-Sensor) can publish a device event that changes the value of the attribute.  This can't be done through pysmartthings.

**Comment by smathieson** [comment]
Yes, I understand. I actually use this with a smartapp. However, as far as the API is concerned it *should* (please correct me if I am wrong) be possible to read the prsenceSensor state? This is what I am referring to, not updating from pysmartthings, but just reading from pysmartthings. Am I correct?

**Comment by andrewsayre** [comment]
It would show up as the `presence` attribute with either the value `present` or `not present`.  You can access it through:

```python
presence = device.attributes[Attribute.presence].value
```

Or to get a `boolean` value:

```python
is_present = device.is_on(Attribute.presence)
```

**Comment by smathieson** [comment]
Thanks, I figured as much, however it is always shown as false and not part of the dictionary values. I tried even refresh().

Does this work for Mobile Presence?

**Comment by smathieson** [comment]
> It would show up as the `presence` attribute with either the value `present` or `not present`. You can access it through:
> 
> ```python
> presence = device.attributes[Attribute.presence].value
> ```
> 
> Or to get a `boolean` value:
> 
> ```python
> is_present = device.is_on(Attribute.presence)
> ```
Sorry, just for posterity, I forgot to mention, I believe that should be device.status.attributes or device.status.is_on.....

Regards,
Sam.

**Comment by andrewsayre** [comment]
You're right, edited!

> Does this work for Mobile Presence?

Does the device implement `presenceSensor` and is it populating the attribute? (Do you see it in Graph?)

**Comment by smathieson** [comment]
It does:
![Screenshot from 2020-07-27 13-42-22](https://user-images.githubusercontent.com/10979112/88579213-4f323a00-d00f-11ea-8b70-6abb9c1d9b24.png)

**Comment by andrewsayre** [comment]
The screen shot shows `not present` which would be `false` on `device.status.is_on(Attribute.presence)`.  Are you seeing Graph indicated `present` yet after querying or refreshing the status, the device still returns `not present` through pysmartthings?

**Comment by smathieson** [comment]
Andrew, sorry yes. I should have mentioned, right now I am not present, but it does not work when I am present either. I can post another screenshot if you wish, of a different device that IS present, and still returns False. The point being that no matter the presence state, it always returns False.

**Comment by andrewsayre** [comment]
Yes, please show a screen shot from Graph with it showing `present` and not through `pysmartthings`.

**Comment by smathieson** [comment]
Here is a small piece of code I use to test:

`import asyncio
import aiohttp
import pysmartthings
from pysmartthings.capability import Attribute, Capability
from pysmartthings.device import Status, DeviceStatus

st_token = 'a....'

class tester:
    async def getAll(self):
        async with aiohttp.ClientSession() as session:
            self.api = pysmartthings.SmartThings(session, st_token)
            self.apps = await self.api.installed_apps()
            self.devices = await self.api.devices()
            for i in range(0, len(self.devices)):
                print(f'{i}: {self.devices[i].label} ({self.devices[i].device_type_name})')
                if "Samuel" in self.devices[i].label:
                    self.samuel = self.devices[i]
                if "Roxana" in self.devices[i].label:
                    self.roxana = self.devices[i]
            self.samuel.status.is_on(Attribute.presence)
            await self.samuel.refresh()
            print(self.samuel.status.attributes[Attribute.presence].value)
            print(self.samuel.status.is_on(Attribute.presence))
            await self.roxana.refresh()
            print(self.roxana.status.attributes[Attribute.presence].value)
            print(self.roxana.status.is_on(Attribute.presence))

t = tester()

asyncio.run(t.getAll())`

Always results in None, False.

You can see the graph here:
![Screenshot from 2020-07-27 22-30-01](https://user-images.githubusercontent.com/10979112/88616137-f12a4480-d058-11ea-828f-5668147a6e7e.png)
![Screenshot from 2020-07-27 22-30-03](https://user-images.githubusercontent.com/10979112/88616138-f1c2db00-d058-11ea-9c51-476d75f305ae.png)

Regards,
Sam.

**Comment by andrewsayre** [comment]
This issue appears to be stale, if you're still having trouble, open a new one.
