### ISSUE TITLE
FR: Add "TvChannelName" retrieval

### ISSUE THREAD

**Issue by chemelli74** [andrewsayre/pysmartthings#36]
Hi,

would be nice to have not only TvChannel as number but also TvChannelName as string.
Extract from SmartThings API site:

```
tvChannel: 5
tvChannelName: Canale5 HD
```

Simone

**Comment by andrewsayre** [comment]
`tvChannelName` is already supported by the library: https://github.com/andrewsayre/pysmartthings/blob/dev/pysmartthings/capability.py#L127 and https://github.com/andrewsayre/pysmartthings/blob/dev/pysmartthings/capability.py#L342

It doesn't have a dedicated property, but you can easily access it as:
```python
device.status.attributes[Attribute.tv_channel_name].value
```
