### ISSUE TITLE
setColor arguments not working

### ISSUE THREAD

**Issue by alexnoyes** [andrewsayre/pysmartthings#51]
When attempting to change the colour of a LED light strip I receive the following:

`pysmartthings.errors.APIResponseError: Unprocessable Entity (422): {"requestId": "6295EEDA-00BE-4FD4-B38F-6A00406DE356", "error": {"code": "ConstraintViolationError", "message": "The request is malformed.", "details": [{"code": "SizeError", "target": "commands[0].arguments", "message": "commands[0].arguments must have a size between 1 and 1.", "details": []}]}}
`

this is generated from the following command:
```

result = await LED.command("main", "colorControl", "setColor", [10,10])
assert result == True
```

**Comment by atticus88** [comment]
I had the same issue. I ended up using the following work around:
```
await device.status.refresh()
print(device.status.values)
```
It outputs the values needed to set the color with a combination of a couple other commands.
```
defaultdict(<function ...>, {'saturation': 74, 'color': None, 'hue': 52, 'switch': 'off', 'checkInterval': 720, 'healthStatus': None, 'DeviceWatch-Enroll': None, 'DeviceWatch-DeviceStatus': None, 'level': 100, 'colorTemperature': 3080})
```
Example:
```
await d.command("main", "switch", "on")
await d.command("main", "colorControl", "setHue", [52])
await d.command("main", "colorControl", "setSaturation", [74])
```

**Comment by andrewsayre** [comment]
From what I can see, this should work, but the error `commands[0].arguments must have a size between 1 and 1` which comes back from the API dones't make sense. If calling the individual commands works, that seems like a valid work around.

FWIW there are wrapper methods for these operations:
```
device.set_color(hue: Optional[float] = None, saturation: Optional[float] = None, color_hex: Optional[str] = None, set_status: bool = False)
device.set_hue(hue: int, set_status: bool = False)
device.set_saturation(saturation: int, set_status: bool = False)
device.switch_on(set_status: bool = False)
device.switch_off(set_status: bool = False)
```

**Comment by alexnoyes** [comment]
Thanks for the comments Andrew. I am still struggling with these hue and saturation operations.

Here is my code:

`        await LED.switch_off()
        print(LED.status.values)
        await LED.switch_on()
        print(LED.status.values)
        await LED.set_hue(96.98276095920139)
        print(LED.status.values)
        await LED.set_saturation(90.98039)
        print(LED.status.values)
        await LED.status.refresh()
        print(LED.status.values)
`

and here is the outcome:

`defaultdict(<function DeviceStatusBase.values.<locals>.<lambda> at 0xb5ab2a08>, {'saturation': 3.1372552, 'color': None, 'hue': 68.75, 'checkInterval': 60, 'healthStatus': None, 'DeviceWatch-Enroll': None, 'DeviceWatch-DeviceStatus': 'online', 'level': 100, 'switch': 'on'})
defaultdict(<function DeviceStatusBase.values.<locals>.<lambda> at 0xb5ab2a08>, {'saturation': 3.1372552, 'color': None, 'hue': 68.75, 'checkInterval': 60, 'healthStatus': None, 'DeviceWatch-Enroll': None, 'DeviceWatch-DeviceStatus': 'online', 'level': 100, 'switch': 'on'})
defaultdict(<function DeviceStatusBase.values.<locals>.<lambda> at 0xb5ab2a08>, {'saturation': 3.1372552, 'color': None, 'hue': 68.75, 'checkInterval': 60, 'healthStatus': None, 'DeviceWatch-Enroll': None, 'DeviceWatch-DeviceStatus': 'online', 'level': 100, 'switch': 'on'})
defaultdict(<function DeviceStatusBase.values.<locals>.<lambda> at 0xb5ab2a08>, {'saturation': 3.1372552, 'color': None, 'hue': 68.75, 'checkInterval': 60, 'healthStatus': None, 'DeviceWatch-Enroll': None, 'DeviceWatch-DeviceStatus': 'online', 'level': 100, 'switch': 'on'})
defaultdict(<function DeviceStatusBase.values.<locals>.<lambda> at 0xb5ab2a08>, {'saturation': 3.1372552, 'color': None, 'hue': 68.75, 'checkInterval': 60, 'healthStatus': None, 'DeviceWatch-Enroll': None, 'DeviceWatch-DeviceStatus': 'online', 'level': 100, 'switch': 'on'})
defaultdict(<function DeviceStatusBase.values.<locals>.<lambda> at 0xb5ab2a08>, {'saturation': 3.1372552, 'color': None, 'hue': 68.75, 'checkInterval': 60, 'healthStatus': None, 'DeviceWatch-Enroll': None, 'DeviceWatch-DeviceStatus': 'online', 'level': 100, 'switch': 'on'})
`
One thing I note is that I switch off the device with LED.switch_off and that works; so does switching on the device.
It just seems that I am unable to set any colours still :( 

I am able to control the device using the SmartThings app (including colour and brightness)

Any ideas?

**Comment by alexnoyes** [comment]
OK so I have a solution.
The set_hue and set_saturation does not work for my LED strip at all.
However, set_color(x, y) does.
A bit fiddly to get the values as they are %'s but got it working in the end!
set_color is setting the saturation and hue perfectly to the colours I want.
