### ISSUE TITLE
Location API issues?

### ISSUE THREAD

**Issue by rtw819** [andrewsayre/pysmartthings#56]
I seem to be having issues with using the location API.  Sample code snippet from what was attempted below. Given that other API functions do work, e.g. I can use the devices() calls for listing devices, and the device.command() calls to turn things off/on, etc. successfully.

I do only have a single location configured in my SmartThings environment.  Perhaps that has something to do with it?  Though, I am wondering if something has changed about the ST implementation of the Locations API somehow?

```
try:
    locations = await api.locations()
    print(len(locations))
    location = locations[0]
    print(location.name)
    print(location.location_id)
except Exception as e:
    print("\n# Location API FAIL: %s\n" % e)
```

The locations API call attempts consistently fail with a 403:

Location API FAIL: 403, message='Forbidden', url=URL('https://api.smartthings.com/v1/locations')

If I'm not missing something obvious, this appears to be a bug -- as it should just work based on what's shown here:
    [https://developer-preview.smartthings.com/api/public/#operation/listLocations](url)

Thoughts?

**Comment by posborne** [comment]
Hi @rtw819, it's probably worth double checking your access token to ensure that it has the right scopes to list locations.  https://account.smartthings.com/tokens
