### ISSUE TITLE
Example for Subsription

### ISSUE THREAD

**Issue by NickWaterton** [andrewsayre/pysmartthings#65]
Does anyone have an example of how to subscribe to a capability?

**Comment by ranhorev** [comment]
@NickWaterton Is it possible you address the wrong repository? this is python code is meant to retrieve information from ST HUB and not subscribe to events

**Comment by NickWaterton** [comment]
What does item 7 below refer to then?

The package is still in beta, but the following features are available:

Locations: List, Get
Rooms: List, Get, Create, Update, Deletegit
Devices: List, Get, Command, Status
Apps: List, Get, Create, Update, Delete, Settings Get & Update, OAuth: Get, Update, & Generate
InstalledApps: List, Get, Delete
Subscriptions: List, Get, Create, Delete, Delete All
Scenes: List, Execute
OAuth: Generate refresh/access token pair

Also, this code retrieves data from the smarthings cloud, not hubs. Maybe it does both.

I can retrieve my TV settings (and set them), but I’m looking for a notification when the inputSource of my TV changes, this is achieved via a SmartApp subscription.

The explanation on what a SmartApp is, and how a subscription works is very confusing, and all the links to explanatory documentation are dead.

As subscriptions are a feature here, and exist in the library, I was hoping someone could explain how to use them.

**Comment by ranhorev** [comment]
@NickWaterton Sorry I was absolutely wrong, this code does handle subscriptions (for some reason I couldn't find it before in the code, must have been tired)
I agree with you this is all very confusing along with the ST documentation. I am personally sorry for choosing to go with ST but it's hard for me to throw down the drain the money spent so I still try...
Try to go over the following it might help you:
https://developer-preview.smartthings.com/docs/connected-services/subscriptions/#subscriptions-api-basics
https://developer-preview.smartthings.com/api/public/#operation/listSubscriptions

and you can take a look at the subscription test in the code to see how it was used;
subscirption.py
and test_create_subscription in test_smartthtings..
may the force be with you...

**Comment by NickWaterton** [comment]
Thanks for the info.

What I’m doing is updating a Samsung TV OpenHAB binding, which is written in Java.

Right now, I’m polling the `devices` api to get the state of some items not exposed by the TV websockets interface (input source for example).

I was hoping that creating a subscription would mean I didn’t have to poll as often (I’m not hitting the rate limit though).

I know Python (and asyncio) better than Java, so I was thinking to put a test program together in Python, to see if subscriptions is a better model than polling.

I already have an asyncio test bed program in Python 3.8 for testing the TV websocket interface (which is mostly undocumented, so it involves a lot of trial and error). This module looked like a good fit to test things out.

I’ll let you know how it goes armed with this new info.

**Comment by andrewsayre** [comment]
@NickWaterton You'll want to take a look at the SmartThings developer documentation, [specifically for SmartApps](https://developer-preview.smartthings.com/docs/connected-services/smartapp-basics/). This library facilitates the creation of subscriptions, but is not the receiver of push updates. You'll need to integrate the `pysmartapp` library, host a webhook URL that meets the ST requirements, and setup, install, and authorize a SmartApp. The documentation is the place to start with the concepts and overall architecture.
